### ISSUE TITLE
【Feature Request】请支持parsec-vdd v0.45

### ISSUE THREAD

**Issue by bobwng** [HaliComing/parsec-vdd-cli#1]
使用parsec-vdd v0.45，点击.bat文件后，出现下面成功提示，但实际上未添加成功：

<img width="409" alt="截屏2024-07-02 13 41 05" src="https://github.com/HaliComing/parsec-vdd-cli/assets/81165201/9083d333-4166-41e5-81e3-c98b3a4d7dd1">

备注：
我的服务器没有连接显示器，是使用远程终端连上去使用的。

**Comment by bobwng** [comment]
再次测试，发现是支持的。
只不过parsec-vdd的GUI显示不出来新增的显示器。

**Comment by HaliComing** [comment]
0.41和0.45的驱动应该是兼容的。

**Comment by bobwng** [comment]
> 0.41和0.45的驱动应该是兼容的。

嗯，现在添加成功了，windows的设置里面也看得到新增的显示器。就是parsec-vdd的GUI里面看不到新添加的显示器，也就不能做更改分辨率等操作。只能通过windows的settings来修改。

**Comment by HaliComing** [comment]
好像驱动中没有获取已添加显示器列表相关的接口，目前这些数据都是CLI或GUI应用里存储的。等待作者Parsec Virtual Display的进一步更新吧。
