### ISSUE TITLE
Custom resolution cannot take effect

### ISSUE THREAD

**Issue by hututuo** [HaliComing/parsec-vdd-cli#2]
The custom resolution has been set, but there is no response when the custom resolution is selected after creating the monitor (the options in the right-click menu have been changed, but the actual resolution has not been changed)thanks

https://github.com/user-attachments/assets/f6225f3c-a70e-46e6-a7cc-bc1c65c9532b

**Comment by HaliComing** [comment]
Please submit your questions [here](https://github.com/nomi-san/parsec-vdd). thanks
